### ISSUE TITLE
MinMaxLocScalar missing template argument

### ISSUE THREAD

**Issue by Azrael3000** [kokkos/kokkos-core-wiki#110]
https://github.com/kokkos/kokkos-core-wiki/blame/main/docs/source/API/core/builtinreducers/MinMaxLocScalar.md#L21

is missing the template argument for the index type.

**Comment by dalg24** [comment]
Would you like to open a PR to fix it?  Let us know if you are not able to and we will assign someone else.

**Comment by Azrael3000** [comment]
Done as requested
