### ISSUE TITLE
MDRangePolicy documentation has an example usage that can throw a deprecation warning

### ISSUE THREAD

**Issue by ElisabethGiem** [kokkos/kokkos-core-wiki#118]
https://kokkos.github.io/kokkos-core-wiki/API/core/policies/MDRangePolicy.html

Following the example usage in the first example under MDRangePolicy throws a deprecation warning for Kokkos::Rank in the current develop branch.

**Comment by dalg24** [comment]
Did you qualify with `Kokkos::Experimental::`?

**Comment by ElisabethGiem** [comment]
This comment led me to the root cause of the issue, which was user error: linking through a bunch of headers to KokkosExp_MDRangePolicy.hpp improperly. A purge of private headers fixed the problem.
