### ISSUE TITLE
Edit button is being duplicated every time the documentation is rebuilt

### ISSUE THREAD

**Issue by dalg24** [kokkos/kokkos-core-wiki#119]
I can live with it but I figured it might be something that is not too hard to fix.
All pages that are not modified get an extra edit button every time the documentation is re-built.

**Comment by fnrizzi** [comment]
@dalg24 we are working on this

**Comment by marcinwrobel1986** [comment]
> I can live with it but I figured it might be something that is not too hard to fix. All pages that are not modified get an extra edit button every time the documentation is re-built.

@dalg24 could you please precise when that happend?

My assumptions are as follows:
- I have reviewed the [Kokkos wiki page](https://kokkos.github.io/kokkos-core-wiki/index.html) and everything there seems ok
- I think the problem occurs only locally, why?:
  - you asked me in this [PR](https://github.com/kokkos/kokkos-core-wiki/pull/109) to add generation of edit button under html section in make file (current Makefile below):
  ```Makefile
  html:
	sphinx-build -b html ./source/ ./generated_docs/
	python3 ./source/edit_button_handler.py

  clean:
	rm -rf ./generated_docs/
  ```
  - after `make html` `Sphinx` is probably looking for changes and finds them only in modified files, so it overwrites only these files, but the python script `edit_button_handler.py` is run and it adds a button to all the files. So when a file was overwritten by `Sphinx` it will have only one edit button, but the other ones will have two

Solution to that would be:
- run `make clean` command before running `make html`
- I could add a `check` to the python script if the button already exists

I see no danger that the documentation deployed to the GitHub pages will have more than one edit button, but it could be improved.

Damien, please let me know if I should add this check to the python script and please also check if running `make clean` before generationg documentation helps. Thanks.

**Comment by dalg24** [comment]
> @dalg24 could you please precise when that happend?
> 
> My assumptions are as follows:
> 
> * I have reviewed the [Kokkos wiki page](https://kokkos.github.io/kokkos-core-wiki/index.html) and everything there seems ok

Yes of course because when generating it we do not rebuild, we generate it from a clean state.


> * I think the problem occurs only locally

Yes if by that you mean when one re-builds.

Instructions to reproduce are as simple as
```
cd docs
make clean
make
make
```
which yields
<img width="1272" alt="Screen Shot 2022-07-27 at 11 22 52 AM" src="https://user-images.githubusercontent.com/296978/181286183-fb84e582-a9a0-4b42-8697-5a94dc56efe2.png">

> Solution to that would be:
>
> * run make clean command before running make html

That is inefficient.
```
make  9.92s user 0.30s system 98% cpu 10.351 total
vs the 2nd time around
make  0.30s user 0.08s system 76% cpu 0.500 total
```
I would rather see two buttons when I do local edits than wait.

> * I could add a check to the python script if the button already exists

That would be nice although, as I stated in the description, I can live with the bug if it is too hard to fix properly (meaning I do not see "building from a clean state" as an acceptable resolution)

**Comment by marcinwrobel1986** [comment]
Ok, thanks for the answer.
It should be pretty easy, I will just check if the button exists in html already, when positive, then it will jump to the next file.
Will be done tomorrow! Thanks.
