### ISSUE TITLE
sphinx porting stage2: update API pages to use sphinx syntax 

### ISSUE THREAD

**Issue by fnrizzi** [kokkos/kokkos-core-wiki#120]
- make a list of the API pages/features that need to be updated in priority order
  1. `View`
  2. all the ones inside [containers](https://kokkos.github.io/kokkos-core-wiki/API/containers-index.html)
  3. convert all parallel dispatch
  4. TBD
- after the list is approved by the team, make PR for each one to convert it from the "old" syntax to the "new" syntax 

By "new syntax" we mean the syntax that @nmm0 proposed to use, see [here](https://github.com/nmm0/kokkos-doc-test/blob/main/test_nm/source/api_reference/view.rst)

**Comment by marcinwrobel1986** [comment]
## i. Highest priority:

| File name                                                        | Doc title | Done with PR |
|------------------------------------------------------------------| --------- | ------------ |
| `building.md`                                                    | [Build, Install and Use](https://kokkos.github.io/kokkos-core-wiki/building.html) | |
| `API/alphabetical.md`                                            | [API in Alphabetical Order](https://kokkos.github.io/kokkos-core-wiki/API/alphabetical.html) | |
| `ProgrammingGuide/Atomic-Operations.md`                          | [Atomic Operations](https://kokkos.github.io/kokkos-core-wiki/ProgrammingGuide/Atomic-Operations.html) | |
| `ProgrammingGuide/Compiling.md`                                  | [Compiling](https://kokkos.github.io/kokkos-core-wiki/ProgrammingGuide/Compiling.html) | |
| `ProgrammingGuide/HierarchicalParallelism.md`                    | [Hierarchical Parallelism](https://kokkos.github.io/kokkos-core-wiki/ProgrammingGuide/HierarchicalParallelism.html) | |
| `ProgrammingGuide/Initialization.md`                             | [Initialization](https://kokkos.github.io/kokkos-core-wiki/ProgrammingGuide/Initialization.html) | |
| `ProgrammingGuide/Interoperability.md`                           | [Interoperability and Legacy Codes](https://kokkos.github.io/kokkos-core-wiki/ProgrammingGuide/Interoperability.html) | |
| `ProgrammingGuide/Introduction.md`                               | [Introduction](https://kokkos.github.io/kokkos-core-wiki/ProgrammingGuide/Introduction.html) | |
| `ProgrammingGuide/Kokkos-and-Virtual-Functions.md`               | [Kokkos and Virtual Functions](https://kokkos.github.io/kokkos-core-wiki/ProgrammingGuide/Kokkos-and-Virtual-Functions.html) | |
| `ProgrammingGuide/Machine-Model.md`                              | [Machine Model](https://kokkos.github.io/kokkos-core-wiki/ProgrammingGuide/Machine-Model.html) | |
| `ProgrammingGuide/ParallelDispatch.md`                           | [Parallel dispatch](https://kokkos.github.io/kokkos-core-wiki/ProgrammingGuide/ParallelDispatch.html) | |
| `ProgrammingGuide/ProgrammingModel.md`                           | [Programming Model](https://kokkos.github.io/kokkos-core-wiki/ProgrammingGuide/ProgrammingModel.html) | |
| `ProgrammingGuide/Subviews.md`                                   | [Subviews](https://kokkos.github.io/kokkos-core-wiki/ProgrammingGuide/Subviews.html) | |
| `ProgrammingGuide/View.md`                                       | [View: Multidimensional array](https://kokkos.github.io/kokkos-core-wiki/ProgrammingGuide/View.html) | |
| `testing-and-issue-tracking/Requirements-Issues-and-Feedback.md` | [Requirements, Issues and Feedback](https://kokkos.github.io/kokkos-core-wiki/testing-and-issue-tracking/Requirements-Issues-and-Feedback.html) | |
| `testing-and-issue-tracking/Testing-Process-Details.md`          | [Attachments](https://kokkos.github.io/kokkos-core-wiki/testing-and-issue-tracking/Testing-Process-Details.html) | |
| `testing-and-issue-tracking/Testing-Processes.md`                | [Kokkos Testing Processes and Change Process](https://kokkos.github.io/kokkos-core-wiki/testing-and-issue-tracking/Testing-Processes.html) | |
| `testing-and-issue-tracking/Testing-Workflow-Components.md`      | [Kokkos Testing Workflow Components](https://kokkos.github.io/kokkos-core-wiki/testing-and-issue-tracking/Testing-Workflow-Components.html) | |
| `usecases/Average-To-Nodes.md`                                   | [ScatterView averaging elements to nodes](https://kokkos.github.io/kokkos-core-wiki/usecases/Average-To-Nodes.html) | |
| `usecases/Kokkos-Fortran-Interoperability.md`                    | [Fortran Interop Use Case](https://kokkos.github.io/kokkos-core-wiki/usecases/Kokkos-Fortran-Interoperability.html) | |
| `usecases/MDRangePolicy.md`                                      | [MDRangePolicy Use Case](https://kokkos.github.io/kokkos-core-wiki/usecases/MDRangePolicy.html) | |
| `usecases/MPI-Halo-Exchange.md`                                  | [MPI Halo Exchange](https://kokkos.github.io/kokkos-core-wiki/usecases/MPI-Halo-Exchange.html) | |
| `usecases/OverlappingHostAndDeviceWork.md`                       | [Overlapping Host and Device work](https://kokkos.github.io/kokkos-core-wiki/usecases/OverlappingHostAndDeviceWork.html) | |
| `usecases/SoA-and-AoSoA-with-Cabana.md`                          | [Array of Structures and Structure of Arrays with Cabana](https://kokkos.github.io/kokkos-core-wiki/usecases/SoA-and-AoSoA-with-Cabana.html) | |
| `usecases/TaggedOperators.md`                                    | [Tagged Operators](https://kokkos.github.io/kokkos-core-wiki/usecases/TaggedOperators.html) | |
| `usecases/Tasking.md`                                            | [Kokkos Tasking Use Case](https://kokkos.github.io/kokkos-core-wiki/usecases/Tasking.html) | |
| `usecases/VirtualFunctions.md`                                   | [Virtual Functions](https://kokkos.github.io/kokkos-core-wiki/usecases/VirtualFunctions.html) | |
| `API/core/Detection-Idiom.md`                                    | [Detection Idiom](https://kokkos.github.io/kokkos-core-wiki/API/core/Detection-Idiom.html) | |
| `API/core/KokkosConcepts.md`                                     | [Kokkos Concepts](https://kokkos.github.io/kokkos-core-wiki/API/core/KokkosConcepts.html) | |
| `API/core/Macros.md`                                             | [Macros](https://kokkos.github.io/kokkos-core-wiki/API/core/Macros.html) | |
| `API/core/Task-Parallelism.md`                                   | [Task-Parallelism](https://kokkos.github.io/kokkos-core-wiki/API/core/Task-Parallelism.html) | |
| `API/core/Traits.md`                                             | [Traits](https://kokkos.github.io/kokkos-core-wiki/API/core/Traits.html) | |

## ii. High priority:

| File name                                                                          | Doc title | Done with PR |
|------------------------------------------------------------------------------------| --------- | ------------ |
| `ProgrammingGuide/Custom-Reductions-Built-In-Reducers.md`                          | [Built-In-Reducers](https://kokkos.github.io/kokkos-core-wiki/ProgrammingGuide/Custom-Reductions-Built-In-Reducers.html) | |
| `ProgrammingGuide/Custom-Reductions-Built-In-Reducers-with-Custom-Scalar-Types.md` | [Built-In Reducers with Custom Scalar Types](https://kokkos.github.io/kokkos-core-wiki/ProgrammingGuide/Custom-Reductions-Built-In-Reducers-with-Custom-Scalar-Types.html) | |
| `ProgrammingGuide/Custom-Reductions-Custom-Reducers.md`                            | [Custom Reducers](https://kokkos.github.io/kokkos-core-wiki/ProgrammingGuide/Custom-Reductions-Custom-Reducers.html) | |
| `API/containers/Bitset.md`                                                         | [Bitset](https://kokkos.github.io/kokkos-core-wiki/API/containers/Bitset.html) | |
| `API/containers/DualView.md`                                                       | [DualView](https://kokkos.github.io/kokkos-core-wiki/API/containers/DualView.html) | |
| `API/containers/DynamicView.md`                                                    | [DynamicView](https://kokkos.github.io/kokkos-core-wiki/API/containers/DynamicView.html) | |
| `API/containers/DynRankView.md`                                                    | [DynRankView](https://kokkos.github.io/kokkos-core-wiki/API/containers/DynRankView.html) | |
| `API/containers/Offset-View.md`                                                    | [OffsetView](https://kokkos.github.io/kokkos-core-wiki/API/containers/Offset-View.html) | |
| `API/containers/ScatterView.md`                                                    | [ScatterView](https://kokkos.github.io/kokkos-core-wiki/API/containers/ScatterView.html) | |
| `API/containers/StaticCrsGraph.md`                                                 | [StaticCrsGraph](https://kokkos.github.io/kokkos-core-wiki/API/containers/StaticCrsGraph.html) | |
| `API/containers/Unordered-Map.md`                                                  | [UnorderedMap](https://kokkos.github.io/kokkos-core-wiki/API/containers/Unordered-Map.html) | |
| `API/containers/vector.md`                                                         | [vector](https://kokkos.github.io/kokkos-core-wiki/API/containers/vector.html) | |
| `API/core/execution_spaces.md`                                                     | [Execution Spaces](https://kokkos.github.io/kokkos-core-wiki/API/core/execution_spaces.html) | |
| `API/core/memory_spaces.md`                                                        | [Memory Spaces](https://kokkos.github.io/kokkos-core-wiki/API/core/memory_spaces.html) | |
| `API/core/SpaceAccessibility.md`                                                   | [Space Accessibility](https://kokkos.github.io/kokkos-core-wiki/API/core/SpaceAccessibility.html) | |
| `API/algorithms/Random-Number.md`                                                  | [Random-Number](https://kokkos.github.io/kokkos-core-wiki/API/algorithms/Random-Number.html) | |
| `API/algorithms/Sort.md`                                                           | [Sort](https://kokkos.github.io/kokkos-core-wiki/API/algorithms/Sort.html) | |

## iii. Medium priority:

| File name                                                | Doc title | Done with PR |
|----------------------------------------------------------| --------- | ------------ |
| `API/algorithms/std-algorithms/Iterators.md`             | [Iterators](https://kokkos.github.io/kokkos-core-wiki/API/algorithms/std-algorithms/Iterators.html) | |
| `API/algorithms/std-algorithms/StdMinMaxElement.md`      | [Minimum/maximum](https://kokkos.github.io/kokkos-core-wiki/API/algorithms/std-algorithms/StdMinMaxElement.html) | |
| `API/algorithms/std-algorithms/StdModSeq.md`             | [Modifying Sequence](https://kokkos.github.io/kokkos-core-wiki/API/algorithms/std-algorithms/StdModSeq.html) | |
| `API/algorithms/std-algorithms/StdNonModSeq.md`          | [NonModifying Sequence](https://kokkos.github.io/kokkos-core-wiki/API/algorithms/std-algorithms/StdNonModSeq.html) | |
| `API/algorithms/std-algorithms/StdNumeric.md`            | [Numeric](https://kokkos.github.io/kokkos-core-wiki/API/algorithms/std-algorithms/StdNumeric.html) | |
| `API/algorithms/std-algorithms/StdPartioningOps.md`      | [Partitioning](https://kokkos.github.io/kokkos-core-wiki/API/algorithms/std-algorithms/StdPartioningOps.html) | |
| `API/algorithms/std-algorithms/StdSorting.md`            | [Sorting](https://kokkos.github.io/kokkos-core-wiki/API/algorithms/std-algorithms/StdSorting.html) | |
| `API/core/atomics/atomic_compare_exchange.md`            | [atomic_compare_exchange](https://kokkos.github.io/kokkos-core-wiki/API/core/atomics/atomic_compare_exchange.html) | |
| `API/core/atomics/atomic_compare_exchange_strong.md`     | [atomic_compare_exchange_strong](https://kokkos.github.io/kokkos-core-wiki/API/core/atomics/atomic_compare_exchange_strong.html) | |
| `API/core/atomics/atomic_exchange.md`                    | [atomic_exchange](https://kokkos.github.io/kokkos-core-wiki/API/core/atomics/atomic_exchange.html) | |
| `API/core/atomics/atomic_fetch_op.md`                    | [atomic_fetch_[op]](https://kokkos.github.io/kokkos-core-wiki/API/core/atomics/atomic_fetch_op.html) | |
| `API/core/atomics/atomic_load.md`                        | [atomic_load](https://kokkos.github.io/kokkos-core-wiki/API/core/atomics/atomic_load.html) | |
| `API/core/atomics/atomic_op.md`                          | [atomic_[op]](https://kokkos.github.io/kokkos-core-wiki/API/core/atomics/atomic_op.html) | |
| `API/core/atomics/atomic_op_fetch.md`                    | [atomic_[op]_fetch](https://kokkos.github.io/kokkos-core-wiki/API/core/atomics/atomic_op_fetch.html) | |
| `API/core/atomics/atomic_store.md`                       | [atomic_store](https://kokkos.github.io/kokkos-core-wiki/API/core/atomics/atomic_store.html) | |
| `API/core/builtinreducers/ReducerConcept.md`             | [ReducerConcept](https://kokkos.github.io/kokkos-core-wiki/API/core/builtinreducers/ReducerConcept.html) | |
| `API/core/builtinreducers/BAnd.md`                       | [BAnd](https://kokkos.github.io/kokkos-core-wiki/API/core/builtinreducers/BAnd.html) | |
| `API/core/builtinreducers/BOr.md`                        | [BOr](https://kokkos.github.io/kokkos-core-wiki/API/core/builtinreducers/BOr.html) | |
| `API/core/builtinreducers/LAnd.md`                       | [LAnd](https://kokkos.github.io/kokkos-core-wiki/API/core/builtinreducers/LAnd.html) | |
| `API/core/builtinreducers/LOr.md`                        | [LOr](https://kokkos.github.io/kokkos-core-wiki/API/core/builtinreducers/LOr.html) | |
| `API/core/builtinreducers/Max.md`                        | [Max](https://kokkos.github.io/kokkos-core-wiki/API/core/builtinreducers/Max.html) | |
| `API/core/builtinreducers/MaxLoc.md`                     | [MaxLoc](https://kokkos.github.io/kokkos-core-wiki/API/core/builtinreducers/MaxLoc.html) | |
| `API/core/builtinreducers/Min.md`                        | [Min](https://kokkos.github.io/kokkos-core-wiki/API/core/builtinreducers/Min.html) | |
| `API/core/builtinreducers/MinLoc.md`                     | [MinLoc](https://kokkos.github.io/kokkos-core-wiki/API/core/builtinreducers/MinLoc.html) | |
| `API/core/builtinreducers/MinMax.md`                     | [MinMax](https://kokkos.github.io/kokkos-core-wiki/API/core/builtinreducers/MinMax.html) | |
| `API/core/builtinreducers/MinMaxLoc.md`                  | [MinMaxLoc](https://kokkos.github.io/kokkos-core-wiki/API/core/builtinreducers/MinMaxLoc.html) | |
| `API/core/builtinreducers/Prod.md`                       | [Prod](https://kokkos.github.io/kokkos-core-wiki/API/core/builtinreducers/Prod.html) | |
| `API/core/builtinreducers/Sum.md`                        | [Sum](https://kokkos.github.io/kokkos-core-wiki/API/core/builtinreducers/Sum.html) | |
| `API/core/c_style_memory_management/free.md`             | [kokkos_free](https://kokkos.github.io/kokkos-core-wiki/API/core/c_style_memory_management/free.html) | |
| `API/core/c_style_memory_management/malloc.md`           | [kokkos_malloc](https://kokkos.github.io/kokkos-core-wiki/API/core/c_style_memory_management/malloc.html) | |
| `API/core/c_style_memory_management/realloc.md`          | [kokkos_realloc](https://kokkos.github.io/kokkos-core-wiki/API/core/c_style_memory_management/realloc.html) | |
| `API/core/initialize_finalize/finalize.md`               | [finalize](https://kokkos.github.io/kokkos-core-wiki/API/core/initialize_finalize/finalize.html) | |
| `API/core/initialize_finalize/initialize.md`             | [initialize](https://kokkos.github.io/kokkos-core-wiki/API/core/initialize_finalize/initialize.html) | |
| `API/core/initialize_finalize/InitializationSettings.md` | [InitializationSettings](https://kokkos.github.io/kokkos-core-wiki/API/core/initialize_finalize/InitializationSettings.html) | |
| `API/core/initialize_finalize/ScopeGuard.md`             | [ScopeGuard](https://kokkos.github.io/kokkos-core-wiki/API/core/initialize_finalize/ScopeGuard.html) | |
| `API/core/numerics/mathematical-constants.md`            | [Mathematical constants](https://kokkos.github.io/kokkos-core-wiki/API/core/numerics/mathematical-constants.html) | |
| `API/core/numerics/mathematical-functions.md`            | [Common math functions](https://kokkos.github.io/kokkos-core-wiki/API/core/numerics/mathematical-functions.html) | |
| `API/core/numerics/numeric-traits.md`                    | [Numeric traits](https://kokkos.github.io/kokkos-core-wiki/API/core/numerics/numeric-traits.html) | |
| `API/core/parallel-dispatch/fence.md`                    | [fence()](https://kokkos.github.io/kokkos-core-wiki/API/core/parallel-dispatch/fence.html) | |
| `API/core/parallel-dispatch/parallel_for.md`             | [parallel_for()](https://kokkos.github.io/kokkos-core-wiki/API/core/parallel-dispatch/parallel_for.html) | |
| `API/core/parallel-dispatch/parallel_reduce.md`          | [parallel_reduce()](https://kokkos.github.io/kokkos-core-wiki/API/core/parallel-dispatch/parallel_reduce.html) | |
| `API/core/parallel-dispatch/parallel_scan.md`            | [parallel_scan()](https://kokkos.github.io/kokkos-core-wiki/API/core/parallel-dispatch/parallel_scan.html) | |
| `API/core/parallel-dispatch/ParallelForTag.md`           | [ParallelForTag()](https://kokkos.github.io/kokkos-core-wiki/API/core/parallel-dispatch/ParallelForTag.html) | |
| `API/core/parallel-dispatch/ParallelReduceTag.md`        | [ParallelReduceTag()](https://kokkos.github.io/kokkos-core-wiki/API/core/parallel-dispatch/ParallelReduceTag.html) | |
| `API/core/parallel-dispatch/ParallelScanTag.md`          | [ParallelScanTag()](https://kokkos.github.io/kokkos-core-wiki/API/core/parallel-dispatch/ParallelScanTag.html) | |
| `API/core/policies/ExecutionPolicyConcept.md`            | [ExecutionPolicy](https://kokkos.github.io/kokkos-core-wiki/API/core/policies/ExecutionPolicyConcept.html) | |
| `API/core/policies/MDRangePolicy.md`                     | [MDRangePolicy](https://kokkos.github.io/kokkos-core-wiki/API/core/policies/MDRangePolicy.html) | |
| `API/core/policies/NestedPolicies.md`                    | [NestedPolicies](https://kokkos.github.io/kokkos-core-wiki/API/core/policies/NestedPolicies.html) | |
| `API/core/policies/RangePolicy.md`                       | [RangePolicy](https://kokkos.github.io/kokkos-core-wiki/API/core/policies/RangePolicy.html) | |
| `API/core/policies/TeamHandleConcept.md`                 | [TeamHandleConcept](https://kokkos.github.io/kokkos-core-wiki/API/core/policies/TeamHandleConcept.html) | |
| `API/core/policies/TeamPolicy.md`                        | [TeamPolicy](https://kokkos.github.io/kokkos-core-wiki/API/core/policies/TeamPolicy.html) | |
| `API/core/policies/TeamThreadRange.md`                   | [TeamThreadRange](https://kokkos.github.io/kokkos-core-wiki/API/core/policies/TeamThreadRange.html) | |
| `API/core/policies/TeamVectorRange.md`                   | [TeamVectorRange](https://kokkos.github.io/kokkos-core-wiki/API/core/policies/TeamVectorRange.html) | |
| `API/core/stl-compat/pair.md`                            | [Kokkos::pair](https://kokkos.github.io/kokkos-core-wiki/API/core/stl-compat/pair.html) | |
| `API/core/utilities/abort.md`                            | [Kokkos::abort](https://kokkos.github.io/kokkos-core-wiki/API/core/utilities/abort.html) | |
| `API/core/utilities/complex.md`                          | [Kokkos::complex](https://kokkos.github.io/kokkos-core-wiki/API/core/utilities/complex.html) | |
| `API/core/utilities/timer.md`                            | [Kokkos::Timer](https://kokkos.github.io/kokkos-core-wiki/API/core/utilities/timer.html) | |
| `API/core/view/create_mirror.md`                         | [create_mirror[_view]](https://kokkos.github.io/kokkos-core-wiki/API/core/view/create_mirror.html) | |
| `API/core/view/deep_copy.md`                             | [deep_copy()](https://kokkos.github.io/kokkos-core-wiki/API/core/view/deep_copy.html) | |
| `API/core/view/layoutLeft.md`                            | [LayoutLeft](https://kokkos.github.io/kokkos-core-wiki/API/core/view/layoutLeft.html) | |
| `API/core/view/layoutRight.md`                           | [LayoutRight](https://kokkos.github.io/kokkos-core-wiki/API/core/view/layoutRight.html) | |
| `API/core/view/layoutStride.md`                          | [LayoutStride](https://kokkos.github.io/kokkos-core-wiki/API/core/view/layoutStride.html) | |
| `API/core/view/realloc.md`                               | [realloc](https://kokkos.github.io/kokkos-core-wiki/API/core/view/realloc.html) | |
| `API/core/view/resize.md`                                | [resize](https://kokkos.github.io/kokkos-core-wiki/API/core/view/resize.html) | |
| `API/core/view/subview.md`                               | [subview](https://kokkos.github.io/kokkos-core-wiki/API/core/view/subview.html) | |
| `API/core/view/view.md`                                  | [View](https://kokkos.github.io/kokkos-core-wiki/API/core/view/view.html) | |
| `API/core/view/view_alloc.md`                            | [view_alloc()](https://kokkos.github.io/kokkos-core-wiki/API/core/view/view_alloc.html) | |
| `API/core/view/view_like.md`                             | [View-like Types](https://kokkos.github.io/kokkos-core-wiki/API/core/view/view_like.html) | |

## iv. Low priority:

| File name             | Doc title | Done with PR |
|-----------------------| --------- | ------------ |
| `API/core/builtinreducers/MinMaxLocScalar.md`      | [MinMaxLocScalar](https://kokkos.github.io/kokkos-core-wiki/API/core/builtinreducers/MinMaxLocScalar.html) | |
| `API/core/builtinreducers/MinMaxScalar.md`         | [MinMaxScalar](https://kokkos.github.io/kokkos-core-wiki/API/core/builtinreducers/MinMaxScalar.html) | |
| `API/core/builtinreducers/ValLocScalar.md`         | [ValLocScalar](https://kokkos.github.io/kokkos-core-wiki/API/core/builtinreducers/ValLocScalar.html) | |

**Comment by marcinwrobel1986** [comment]
Hello,
above is my proposal. Please feel free to edit priorities or let me know, so I will edit them.
I think we need to get track on the changes, that's why I did a table.

I would suggest to do following:

### TODO:
| File name                                                        | Doc title | Done with PR |
|------------------------------------------------------------------| --------- | ------------ |
| `building.md`                                                    | [Build, Install and Use](https://kokkos.github.io/kokkos-core-wiki/building.html) | |

### PR ready for review:
| File name                                                        | Doc title | Done with PR |
|------------------------------------------------------------------| --------- | ------------ |
| `building.md`                                                    | [Build, Install and Use](https://kokkos.github.io/kokkos-core-wiki/building.html) | #100  |

### PR Merged:
| File name                                                        | Doc title | Done with PR |
|------------------------------------------------------------------| --------- | ------------ |
| ~~`building.md`~~                                                | ~~[Build, Install and Use](https://kokkos.github.io/kokkos-core-wiki/building.html)~~ | ~~#100~~ |

**Comment by fnrizzi** [comment]
@marcinwrobel1986 please use the above priority table

**Comment by marcinwrobel1986** [comment]
Hello @fnrizzi @dalg24 ,
I just want to bring your attention to the limitation of `.rst`
In `.md` files we have possibility to link `inline literals` in `.rst` we don't:
- `.md` sample from `/API/core/view/subview`:
![Zrzut ekranu z 2022-08-26 07-31-38](https://user-images.githubusercontent.com/47597569/186829136-e800b1e7-f3b8-424b-a9ed-58325df1c33f.png)

- `.rst` sample from `/API/core/view/subview`:
![Zrzut ekranu z 2022-08-26 07-32-18](https://user-images.githubusercontent.com/47597569/186829223-59f4068c-f8f6-424b-ae6e-b555367a5552.png)

More can be found [here](https://docutils.sourceforge.io/docs/dev/rst/alternatives.html#nested-inline-markup). It looks like it's been on [TODO List](https://docutils.sourceforge.io/docs/dev/rst/alternatives.html#nested-inline-markup) for over 20 years.

**Comment by fnrizzi** [comment]
What do you mean in-line literals? Also, the two images you show look the same to me ? What is the difference?

**Comment by marcinwrobel1986** [comment]
I mean:
- text: Kokkos::ALL
- inline literal: `Kokkos::ALL`

**Comment by fnrizzi** [comment]
pretty much done (except for std algorithms) and PRs are either merged or ready to merge
