### ISSUE TITLE
Templates for marking `deprecated`, `promoted`, etc. in the documentation

### ISSUE THREAD

**Issue by JBludau** [kokkos/kokkos-core-wiki#131]
Since we do not host multiple versions of the documentation, we should think about some easy and transparent way to mark things that changed depending on the `Kokkos` version in our single-source documentation.
To start, I propose the following categories as a discussion starter:

- `promoted` -> things that are moved out of `Experimental` into the main namespace in a version.
- `deprecated` -> things that are deprecated in ... and will be removed in ... 
- `since and until` -> not sure if we need a `until` it is similar to `deprecated`, but a `since` would make sense for newly introduced things
- `behavior change` -> hint on a change of behavior in a certain version (e.g. commandline argument parsing)

We should make this as easy to spot as possible, e.g. the user should see it at first glance when looking at the documentation so users can help themselves. 

For the `HIPSpaces` I already faced this problem and used this (see it as a proposal of how it could look like)
<img width="750" alt="image" src="https://user-images.githubusercontent.com/104908666/182237809-e21ff06f-0e5d-4b3b-8c16-ed121b81f4eb.png">

Damien did something for the documentation of the `ScopeGuard` as a next example
<img width="830" alt="image" src="https://user-images.githubusercontent.com/104908666/182238855-943c3d94-87b5-41c8-9812-c4945f4ac615.png">

**Comment by marcinwrobel1986** [comment]
Hello @JBludau ,

since [Furo theme](https://github.com/pradyunsg/furo) was chosen, IMHO we should checkout what is has to offer.
[Admonitions](https://pradyunsg.me/furo/reference/admonition) seems to be a good choice.
One could try that and check the effect locally. One could find syntax for both *.rst and *.md files. 

For `deprication` maybe use [warning](https://pradyunsg.me/furo/reference/admonitions/#warning) with custom title like:
- rst:
```rst
.. admonition:: Deprecation warning
   :class: warning

   Since Kokkos version 3.7 ...
```

- md:
```md
    ```{admonition} Deprecation warning
    :class: warning

    Since Kokkos version 3.7 ...
    ```
```

For `promoted` maybe use [tip](https://pradyunsg.me/furo/reference/admonitions/#tip) with custom title like:
- rst:
```rst
.. admonition:: Promotion info
   :class: tip

   Since Kokkos version 3.7 ...
```
- md:
```md
    ```{admonition} Promotion info
    :class: tip

    Since Kokkos version 3.7 ...
    ```
```

For `behavior change` maybe use [tip](https://pradyunsg.me/furo/reference/admonitions/#attention) with custom title like:
- rst:
```rst
.. admonition:: Behavior change
   :class: attention

   Since Kokkos version 3.7 ...
```
- md:
```md
    ```{admonition} Behavior change
    :class: attention

    Since Kokkos version 3.7 ...
    ```
```

For `since and until` any other from [Admonitions](https://pradyunsg.me/furo/reference/admonition) which seems appropriate.

Please let me know if you are satisfied with this solution or we should figure out something else.

**Comment by JBludau** [comment]
Yeah, definitely an option. Could you add a render/example of this to make discussing easier? I think it makes sense to choose something that does not disturb the reading too much but appears where people would expect it (some might not read the full text but just look at the first words/the definition). 
For things like behavior change it might be worth having them in a way the users cannot possibly miss it

**Comment by marcinwrobel1986** [comment]
Hello @JBludau ,
please find below proposed above sample use of [Admonitions](https://pradyunsg.me/furo/reference/admonition) in both light and dark theme:
- deprication:
![Zrzut ekranu z 2022-08-03 06-48-07](https://user-images.githubusercontent.com/47597569/182526903-f836edda-fb22-4446-ae7c-0ced7bfaf874.png)
![Zrzut ekranu z 2022-08-03 06-58-08](https://user-images.githubusercontent.com/47597569/182527433-d722b049-3a14-4795-a63d-c78412d2ce80.png)

- promoted:
![Zrzut ekranu z 2022-08-03 06-49-33](https://user-images.githubusercontent.com/47597569/182526960-323eddb7-a239-4c07-a997-953cadae666c.png)
![Zrzut ekranu z 2022-08-03 06-57-44](https://user-images.githubusercontent.com/47597569/182527469-bb3d4839-78b8-4485-b233-e85e3fb4a6da.png)

- behavior change:
![Zrzut ekranu z 2022-08-03 06-50-37](https://user-images.githubusercontent.com/47597569/182527033-5c1e347b-3b87-4e25-8e23-921f8855168c.png)
![Zrzut ekranu z 2022-08-03 06-57-18](https://user-images.githubusercontent.com/47597569/182527491-2a800b8d-148b-4c23-8c1c-2d4fb0daf0e2.png)

**Comment by JBludau** [comment]
thanks @marcinwrobel1986 . what do the others think? I like it for block annotations and warnings we definitely want the user to read. For just giving a promotion info it might be a bit heavy.

Is there a way to annotate something with this inside a text block? This might be easier to read/less disturbing the textflow.

**Comment by marcinwrobel1986** [comment]
@JBludau It seems that [Admonitions](https://pradyunsg.me/furo/reference/admonitions/) could be:
- nested
![Zrzut ekranu z 2022-08-03 16-22-28](https://user-images.githubusercontent.com/47597569/182632903-daab60a4-7e4f-4913-a986-045eac02a7e0.png)
- custimized
![Zrzut ekranu z 2022-08-03 16-23-06](https://user-images.githubusercontent.com/47597569/182633019-2cb6c23b-00be-4a1c-b3e6-66661f690fe4.png)

It seems impossible to put them inside text block, some questions come right away:
- How it would be rendered inside text block?
- It will not be as much visible as in current form, where icon, color and description shout to the reader and are hard to miss

Most regarding [Admonitions](https://pradyunsg.me/furo/reference/admonitions/) were presented here, apart from different color and icons.
If you need any more help, please let me know.

**Comment by ajpowelsnl** [comment]
**CATEGORIES NEEDED:**

- `deprecated` on individual description of the function / member
- `since / until` in the synopsis; ATTN: no `deprecated` in the synopsis;
  - Moving from `Experimental` namespace (e.g., `since` Kokkos-3.7 `until` Kokkos-4.0) to `Kokkos` namespace to track feature evolution
  - General template: Concept, Synopsis, text description; see `Reducers` example;
  - Jakob B. will use `Reducer` example to modify `View` w/ Sphinx syntactic sugar and present in the next documentation session
- `Experimental` namespace banner, similar to `Danger` / `Warning` banners?
- Anytime we change the interface, add to the list of version change directives

**Comment by fnrizzi** [comment]
@JBludau @marcinwrobel1986 I like the admonition to highlight things. IMO, a bit heavier is better than less visible

**Comment by JBludau** [comment]
@marcinwrobel1986 We looked at how the the documentation page for `reducer_concept` looks like if we port it from `md` to `rst` and added the type annotations. The branch can be found [here](https://github.com/JBludau/kokkos-core-wiki/tree/reducer_concept_rst_annotation). 
While comparing the rendered pages to the old version we noticed some things we would like to have:

- more vertical information density
- make `Addition/Removal` and `Deprecation` directives more visually impactful (to have a banner or something similar) -- or maybe even a badge on the method/class which is more space-efficient
- less visual noise (e.g fewer fontstyles/colors for highlighting)
- maybe boxes to allow for more structure in the documentation

Do you know a way to achieve this easily (changing the sphinx style directly/switching to another css file)

**Comment by marcinwrobel1986** [comment]
Hello @JBludau,
I have built docs from your branch and I see what do you mean.
So, as the [Furo theme](https://github.com/pradyunsg/furo) was chosen I guess we have to stick with it, so:
- [Customization options](https://pradyunsg.me/furo/customisation/)
- [Changing colors](https://pradyunsg.me/furo/customisation/colors/)
- [Changing fonts](https://pradyunsg.me/furo/customisation/fonts/)
- [Injecting code](https://pradyunsg.me/furo/customisation/injecting/)
- [Using custom css](https://docs.readthedocs.io/en/stable/guides/adding-custom-css.html) - we already doing it, please see screenshot below (hacks.css):

![Zrzut ekranu z 2022-08-25 08-58-40](https://user-images.githubusercontent.com/47597569/186596631-137ea0d1-538b-4c38-a659-fe8110870e3f.png)

Other Sphinx themes (most recent at the top) could be found [here](https://sphinx-themes.org/), but IMHO they will present similar problems regarding customization. Current [Furo theme](https://github.com/pradyunsg/furo) seems very reasonable regarding customization.

I think the most powerful option could be:
- [Setting CSS variables](https://pradyunsg.me/furo/customisation/#css-variables) in `conf.py` like below (just some sample options):
```Python3
html_theme_options = {
    "light_css_variables": {
        "color-api-name": "green",
        "font-stack": "Helvetica, sans-serif",
        "font-stack--monospace": "Lucida Console, monospace",
        "api-font-size": "82%",
        "font-size--normal": "90%",
        "font-size--small": "83%",
        "admonition-font-size": "1.0rem",
        "admonition-title-font-size": "3.5rem",
    },
}
```

- `furo.css` could be find in `<furo-package-install-path>/furo/theme/furo/static/styles/furo.css` or in `generated_docs/_static/styles/furo.css`

I haven't noticed changes regarding fonts, but font-sizes and font-color differs:

![Zrzut ekranu z 2022-08-25 10-32-00](https://user-images.githubusercontent.com/47597569/186616901-a54ad9e6-e1fb-4827-b20a-ae81f1e05d4c.png)
![Zrzut ekranu z 2022-08-25 10-32-47](https://user-images.githubusercontent.com/47597569/186616966-5dbe46c5-e610-406a-9846-5e51bd86ed84.png)

Admonition size could be customizable as well:
- standard:
![Zrzut ekranu z 2022-08-25 10-49-17](https://user-images.githubusercontent.com/47597569/186620060-6fc02d4d-6f64-4e52-b469-4bbd0d9cb1d9.png)

- changed
![Zrzut ekranu z 2022-08-25 10-47-31](https://user-images.githubusercontent.com/47597569/186619786-6118ed4d-3f72-44d8-9fdd-1edf111dc388.png)

I hope that would help you customize the appearance.
Please let me know if you need any other/additional info.

**Comment by marcinwrobel1986** [comment]
@JBludau regarding boxes, if one has a list and one want's the point from this list to be highlighted together, then one could start a line with two spaces, like:
```rst
List:
  * first point
  * second point
```
Then the list will be highlighted/in a box like below:

![Zrzut ekranu z 2022-08-29 09-45-44](https://user-images.githubusercontent.com/47597569/187152622-42da36d0-5cad-4c2b-9360-040326f720b6.png)
![Zrzut ekranu z 2022-08-29 09-43-46](https://user-images.githubusercontent.com/47597569/187152627-93e1d0a4-550e-4bb1-b7f8-c31593bfd5f8.png)

When one starts right at the beginning of a line, like:
 ```rst
List:
* first point
* second point
```
Then the list will look like below:
![Zrzut ekranu z 2022-08-29 09-45-07](https://user-images.githubusercontent.com/47597569/187153203-e52bcb7b-04b5-415d-a9fc-c92500c8c146.png)
![Zrzut ekranu z 2022-08-29 09-44-14](https://user-images.githubusercontent.com/47597569/187153206-c855c86f-d3dc-4df8-a5d8-8f80284de260.png)

**Comment by JBludau** [comment]
@marcinwrobel1986 @fnrizzi since we are housekeeping ... we can probably close this, as it is captured in #187

**Comment by marcinwrobel1986** [comment]
> @marcinwrobel1986 @fnrizzi since we are housekeeping ... we can probably close this, as it is captured in #187

I agree. I would really appreciate if you could post which of:
- `promoted`
- `since and until`
- `behavior change`
- `experimental`

And how should be supported. I have unfortunately missed a few meetings lately and I am not sure what was/is the agreement regarding adding mentioned directives to `cppkokkos` domain.
