### ISSUE TITLE
Reflect deprecation of need for volatile in reducer-interfacing bits

### ISSUE THREAD

**Issue by PhilMiller** [kokkos/kokkos-core-wiki#151]
Reflect kokkos/kokkos#4077, kokkos/kokkos#4931, kokkos/kokkos#1554, kokkos/kokkos#5194, kokkos/kokkos#5215

**Comment by ajpowelsnl** [comment]
Hi @PhilMiller -- do the PR mentioned above address main points of this issue?  If so, can we close the issue?  If not, can you detail what else needs to be done?

**Comment by masterleinad** [comment]
Fixed by https://github.com/kokkos/kokkos-core-wiki/pull/152 and https://github.com/kokkos/kokkos-core-wiki/pull/185.
