### ISSUE TITLE
create_mirror doesn't reflect ability to accept ViewCtorProp

### ISSUE THREAD

**Issue by PhilMiller** [kokkos/kokkos-core-wiki#159]
Update API/core/view/create_mirror to reflect kokkos/kokkos#5095

**Comment by ajpowelsnl** [comment]
Hi @PhilMiller -- was the `create_mirror` entry edited to reflect the needed changes?   Assuming not, I added to our "TODO" list.

**Comment by PhilMiller** [comment]
I don't know, was it?

**Comment by masterleinad** [comment]
Fixed in #208.
