### ISSUE TITLE
Custom sphinx directive for deprecating a type alias

### ISSUE THREAD

**Issue by marcinwrobel1986** [kokkos/kokkos-core-wiki#166]
# What this issue is about

To show what is needed to define and implement a new custom sphinx directive ``.. cpp:deprecated-type::``.  
(Note that the scope of this is to only look at the customization feasibility, not yet at inlining the text and all other things we discussed. Those will be addressed in different issues).

The goal is to minimize the about of customization we have to do to the sphinx code, and delegate as much as possible of the customization to the html level. 

# Implementation of this custom directive

To support that, we need to modify the `cpp domain` via the following modification in this file `sphinx/domains/cpp.py`

```Python3
# line 3097
	elif objectType == 'deprecated-type':  # just the name
            res.append(symbol.get_full_nested_name().get_id(version))

# line 3129
	elif objectType == 'deprecated-type':  # just the name
            res.append(symbol.get_full_nested_name().get_id(version))

# line 3154
        elif self.declSpecs.outer == 'deprecated-type':
            return '[DEPRECATED]'

# line 4029
	elif self.objectType == 'deprecated-type':
            prefix = self.declaration.get_type_declaration_prefix()
            mainDeclNode += addnodes.desc_sig_keyword(prefix, prefix)
            mainDeclNode += addnodes.desc_sig_space()

# line 6251
        if outer not in ('type', 'member', 'function', 'templateParam', 'deprecated-type'):
            raise Exception('Internal error, unknown outer "%s".' % outer)

# line 6335
        if paramMode not in ('type', 'function', 'operatorCast', 'new', 'deprecated-type'):

# line 6503
        if outer not in ('type', 'member', 'function', 'operatorCast', 'templateParam', 'deprecated-type'):

# line 6507
        if outer in ('type', 'function', 'deprecated-type'):

# line 6522
        elif outer == 'deprecated-type':
            desc = "If just a name"

# line 6537
        elif outer == 'deprecated-type':
            desc = "If typedef-like declaration"

# line 6551
        elif outer == 'deprecated-type':
            header = "Deprecated-type must be either just a name or a "
            header += "typedef-like declaration."

# line 6573
            elif outer == 'deprecated-type':
                paramMode = 'deprecated-type'
                outer = None

# line 6589
        if outer:
            assert outer in ('type', 'member', 'function', 'templateParam', 'deprecated-type')

# line 6963
	if objectType not in ('class', 'union', 'function', 'member', 'type',
                              'concept', 'enum', 'enumerator', 'deprecated-type'):
            raise Exception('Internal error, unknown objectType "%s".' % objectType)
        if directiveType not in ('class', 'struct', 'union', 'function', 'member', 'var', 'type', 'concept', 'enum',
                                 'enum-struct', 'enum-class', 'enumerator', 'deprecated-type'):
            raise Exception('Internal error, unknown directiveType "%s".' % directiveType)

# line 6978
	if objectType in ('type', 'concept', 'member', 'function', 'class', 'deprecated-type'):

# line 7001
	elif objectType == 'deprecated-type':
            prevErrors = []
            pos = self.pos
            try:
                if not templatePrefix:
                    declaration = self._parse_type(named=True, outer='type')
            except DefinitionError as e:
                prevErrors.append((e, "If typedef-like declaration"))
                self.pos = pos
            pos = self.pos
            try:
                if not declaration:
                    declaration = self._parse_type_using()
            except DefinitionError as e:
                self.pos = pos
                prevErrors.append((e, "If type alias or template alias"))
                header = "Error in type declaration."
                raise self._make_multi_error(prevErrors, header) from e

# line 7344
	class CPPDeprecatedTypeObject(CPPObject):
    		object_type = 'deprecated-type'

# line 7794
	'deprecated-type': CPPDeprecatedTypeObject,

# line 7816
	'deprecated-type': CPPXRefRole(),
```

# Example rst source 

```rst
``Kokkos::TestView``
====================

.. role:: cpp(code)
   :language: cpp

Header File: ``Kokkos_Core.hpp``

Class Interface
---------------

.. cpp:class:: template <class DataType, class... Traits> TestView

  A potentially reference counted multi dimensional array with compile time layouts and memory space.
  Its semantics are similar to that of :cpp:`std::shared_ptr`.

  .. rubric:: Public Member Variables

  .. cpp:member:: static constexpr unsigned rank

    the rank of the view (i.e. the dimensionality).

  .. cpp:type:: const_data_type

    The const version of ``DataType``, same as ``data_type`` if that is already const.

  .. cpp:deprecated-type:: some_deprecated_data_type

    The const version of some_deprecated_data_type.
```

# Overwriting the style for this `deprecated` directive

What shown above is just the sphinx syntax, but we also need a final step to change the html similarly 
to how we do the edit buttom. To do that, the code is (which we will put into a file called `change_style_directives.py` or similar): 

```Python3
# ...
# Overwriting the deprecated style
str_to_replace = '<span class="pre">[DEPRECATED]</span>'
replaced_with = '<span class="pre" style="color:#A020F0;font-weight:bold;">[DEPRECATED]</span>'
html_str_replace = html_str_replace.replace(str_to_replace, replaced_with)
```

# Rendered as:

![Zrzut ekranu z 2022-09-13 16-07-10](https://user-images.githubusercontent.com/47597569/189923378-f55b1e5c-88d7-465f-9b43-e7ef71e7df3e.png)
![Zrzut ekranu z 2022-09-13 16-07-20](https://user-images.githubusercontent.com/47597569/189923395-36d78138-b61e-42ab-a2b7-6acc27e2025b.png)

**Comment by fnrizzi** [comment]
@marcinwrobel1986  I think this looks really nice! 
So in order to do this and potentially add more customizations, we would need to fork sphinx and use that fork. 
But I think that could also be a good thing because it might be that other people don't liek the default sphinx syntax/rendering and so we might try to push for this to be adopted by sphinx directly.

**Comment by marcinwrobel1986** [comment]
So, that would need a fork from Sphinx and ideally a PyPi package as well.

**Comment by JBludau** [comment]
thanks for your work, it looks really like what I was hoping for. 
About editing the html after generation ... can't we do that directly when generating the html? Otherwise we would have to change our postprocessing of the html every time sphinx changes the code it generates. But I don't know if that is viable or if we would end up writing our own sphinx style

**Comment by fnrizzi** [comment]
@JBludau thst is something Marcin and I talked about but IMO we should try to minimize how much customization we do to Sphinx. If we keep the distinction between the "implementation" and "appearance", it is much more easily to change the appearance. But we can talk about pros/cons

**Comment by marcinwrobel1986** [comment]
> thanks for your work, it looks really like what I was hoping for. About editing the html after generation ... can't we do that directly when generating the html? Otherwise we would have to change our postprocessing of the html every time sphinx changes the code it generates. But I don't know if that is viable or if we would end up writing our own sphinx style

@JBludau to answer your questions:
- when you use `make html`, what is actually happening underneath is:
```shell
sphinx-build -b html ./source/ ./generated_docs/
python3 ./source/edit_button_handler.py
```
- so back to your question, we are running the script each time docs are generated, that's why I decided to put it there. Just an additional 3 lines
- if we would like to add it directly to Sphinx, that would be way more complicated, time consuming and we would have to add another style to *.css file

**Comment by nmm0** [comment]
> So, that would need a fork from Sphinx and ideally a PyPi package as well.

Could this be done with just a plugin?

**Comment by marcinwrobel1986** [comment]
> > So, that would need a fork from Sphinx and ideally a PyPi package as well.
> 
> Could this be done with just a plugin?

@nmm0  what do you mean by a plugin?

**Comment by nmm0** [comment]
@marcinwrobel1986 check out https://www.sphinx-doc.org/en/master/extdev/index.html

> Here are a few things you can do in an extension:
>
>    Add new [builder](https://www.sphinx-doc.org/en/master/glossary.html#term-builder)s to support new output formats or actions on the parsed documents.
>
>    Register custom reStructuredText roles and directives, extending the markup using the [Docutils markup API](https://www.sphinx-doc.org/en/master/extdev/markupapi.html).
>
>    Add custom code to so-called “hook points” at strategic places throughout the build process, allowing you to register a hook and run specialized code. For example, see the [Sphinx core events](https://www.sphinx-doc.org/en/master/extdev/appapi.html#events).

**Comment by marcinwrobel1986** [comment]
@nmm0 ok Nic thanks, I will check that first thing tomorrow and see if that could work for us.

**Comment by marcinwrobel1986** [comment]
@nmm0 @fnrizzi I was checking the docs today and it seems that making an extension for Sphinx is doable. I will start working on that.

**Comment by fnrizzi** [comment]
thanks!

**Comment by ajpowelsnl** [comment]
@nmm0 , @marcinwrobel1986 -- an easy question (hopefully):  how does one maintain the customization of a plugin / potential drift from the base code of that plugin?  Through a fork?

**Comment by nmm0** [comment]
> @nmm0 , @marcinwrobel1986 -- an easy question (hopefully): how does one maintain the customization of a plugin / potential drift from the base code of that plugin? Through a fork?

@ajpowelsnl the advantage of the plugin is that we don't have to fork anything and reduces our maintenance burden rather than modifying the sphinx base code

**Comment by marcinwrobel1986** [comment]
@fnrizzi I think this issue could be closed as well. PR's with extension are waiting to be merged.
