### ISSUE TITLE
`cppkokkos` extension: status and next steps

### ISSUE THREAD

**Issue by marcinwrobel1986** [kokkos/kokkos-core-wiki#187]
# Scope: creating a customized framework for Kokkos documentation 

This has two main pieces in it: 
- (a) using custom directives at the sphinx level
- (b) customizations done directly at the html level. 
Part (b) is needed/useful if sphinx customizations are not possible at all or when doing so is very complicated. 

# Things done so far 

## 1. Enabled customizations at the sphinx level: what and how

- used the external feature of Sphinx to create a customization capability that allows us to easly add new customizations *without* having to modify the upstream sphinx package/code 

- the goal is to create custom directive for C++ documentation: to do so, we had to make a new "domain name" `cppkokkos` inside of which to create these customizations 

- the PR for this custom domain name lives [HERE](https://github.com/kokkos/kokkos-core-wiki/pull/172): **NOTE**: we need to redo this on top of the latest Sphinx to make sure we are good 

### [DEPRECATED] (`.. cppkokkos:deprecated-type::`)
See example: [HERE](https://github.com/kokkos/kokkos-core-wiki/pull/172)

<img width="631" alt="image" src="https://user-images.githubusercontent.com/18708772/196683790-5e24081d-6af0-4fbc-8d92-a67b66f5b9e2.png">

<img width="611" alt="image" src="https://user-images.githubusercontent.com/18708772/196683459-bcd464f1-72ab-44f7-8414-5233c92ad10a.png">

### [DEPRECATED since X.X.X] (`.. cppkokkos:deprecated-type::`)
See example: [HERE](https://github.com/kokkos/kokkos-core-wiki/pull/172)

<img width="601" alt="image" src="https://user-images.githubusercontent.com/18708772/196683962-18fcb71f-4035-41a6-a174-4158d08dce6a.png">

<img width="591" alt="image" src="https://user-images.githubusercontent.com/18708772/196683915-fa538b68-22d8-4803-8f68-c46fcf345369.png">

### removed rendering word `type` before (`.. cppkokkos:type::`)
![Zrzut ekranu z 2022-10-19 16-10-08](https://user-images.githubusercontent.com/47597569/196715231-a913d15c-7a49-4ccf-928d-10faf95f1f4f.png)
![Zrzut ekranu z 2022-10-19 16-00-26](https://user-images.githubusercontent.com/47597569/196715282-8b960d76-2620-4594-b84c-7a716192bc39.png)
![Zrzut ekranu z 2022-10-19 16-00-11](https://user-images.githubusercontent.com/47597569/196715390-a48dd3ef-8fe2-468c-882b-1c1634c78b7e.png)

## 3. Customizations applied *directly* to the html

- support for custom color for code block directives (postprocessing with `edit_button_handler.py`)

# TODO:
- define which other `code block directives` needs to be supported
- what else should be added to `cppkokkos` extension

### Useful links:
- [Discussion regarding code block directives to be added](https://github.com/kokkos/kokkos-core-wiki/pull/172)
- [Discussion regarding Experimental code block](https://github.com/kokkos/kokkos-core-wiki/issues/167)
- [First discussion regarding code block directives](https://github.com/kokkos/kokkos-core-wiki/issues/131)

Please write in comments if you have already agreed on other directives which should be added to `cppkokkos` extension.
@fnrizzi @crtrott @ajpowelsnl @JBludau @dalg24 @nmm0 @masterleinad

**Comment by JBludau** [comment]
So if my memory is correct we wanted something like this:

- `since` and `until` with version number to introduce new stuff and remove old stuff
- `experimental` to mark stuff that is still in the experimental namespace (if anyone has a better idea to integrate experimental stuff please speak up).
- `Behavior change` I think we are good with the `.. admonition:: Behavior change :class: attention` thing
- `deprecation` we already have the neat solution with the current extension.
