### ISSUE TITLE
`Github` typo on the front page

### ISSUE THREAD

**Issue by cz4rs** [kokkos/kokkos-core-wiki#223]
![image](https://user-images.githubusercontent.com/4639165/207114343-11a0b365-fcee-41a7-9dfd-eafd86f39556.png)

Nitpicking:
This should be `GitHub link` instead of `Github link` everywhere.

**Comment by ajpowelsnl** [comment]
Hi @cz4rs -- Has this problem been corrected?

**Comment by cz4rs** [comment]
> Hi @cz4rs -- Has this problem been corrected?

Nope, it seems like it hasn't. I will take care of this shortly :wink:
