### ISSUE TITLE
Polishing after converting (from .md to .rst) 

### ISSUE THREAD

**Issue by antoinemeyer5** [kokkos/kokkos-core-wiki#269]
Converting documentation files from .md to .rst helps highlight files that are unfinished, outdated, or whose content is not understandable.

These files therefore deserve to be polished. Original comment requesting this issue: https://github.com/kokkos/kokkos-core-wiki/pull/249#pullrequestreview-1250654257

Here is the list of files to polish:

| File name                                                              | Doc title | Message |
|------------------------------------------------------------------| ------------- | ------------- |
| `API/core/SpaceAccessibility.rst`                          | [SpaceAccessibility](https://kokkos.github.io/kokkos-core-wiki/API/core/SpaceAccessibility.html) | |
| `API/core/execution_spaces.rst` | [Execution Spaces](https://kokkos.github.io/kokkos-core-wiki/API/core/execution_spaces.html) | https://github.com/kokkos/kokkos-core-wiki/pull/294#pullrequestreview-1286108701 |
| `API/core/KokkosConcepts.rst` | [Kokkos Concepts](https://kokkos.github.io/kokkos-core-wiki/API/core/KokkosConcepts.html) | |

**Comment by fnrizzi** [comment]
@antoinemeyer5 are these unfinished, outdated, need to be polished or all three?

**Comment by antoinemeyer5** [comment]
> @antoinemeyer5 are these unfinished, outdated, need to be polished or all three?

These need to be polished. I think it's about updating the documentation, fixing spelling mistakes, etc.

**Comment by ajpowelsnl** [comment]
Hi @antoinemeyer5 and @fnrizzi -- how's this effort going?  Do you need help with it?  Can you guesstimate when your first pass of polishing will be done?

**Comment by fnrizzi** [comment]
I think this should be closed for now, we need to define what polishing means for these pages
