### ISSUE TITLE
sphinx  warns about duplicate declarations for overloads sets (e.g. constructor)

### ISSUE THREAD

**Issue by fnrizzi** [kokkos/kokkos-core-wiki#295]
This code:
```
.. cppkokkos:kokkosinlinefunction:: BAnd(value_type& value_);

    * Constructs a reducer which references a local variable as its result location.

.. cppkokkos:kokkosinlinefunction:: BAnd(const result_view_type& value_);

    * Constructs a reducer which references a specific view as its result location.
```
causes this:
```
/Users/fnrizzi/Desktop/work/kokkoscore/kokkos-core-wiki/docs/source/API/core/builtinreducers/BAnd.rst:67: 
WARNING: Duplicate C++ declaration, also defined at API/core/builtinreducers/BAnd:63.
Declaration is '.. cppkokkos:kokkosinlinefunction:: BAnd(const result_view_type& value_);'.
```

need to figure out where this needs to be resolved

**Comment by antoinemeyer5** [comment]
Several possible solutions after looking quickly:

- you can suppress warnings with the addition of **suppress_warnings** tag in the configuration (very bad idea I think)
https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-suppress_warnings

- there may have been a track on the side of the Sphinx version but we are using version 5.0.1 so we should be fine
https://lore.kernel.org/all/564cbd05-8788-9223-1ecc-59e7fc41b46a@gmail.com/

- cool issue that looks a lot like ours
https://github.com/sphinx-doc/sphinx/issues/11174
Unfortunately the guy called twice **self.state.nested_parse(self.content, self.content_offset, contentnode)** so it's normal that it makes a duplication... I went to look and in our code (here: https://github.com/antoinemeyer5/kokkos-core-wiki/blob/main/docs/source/_ext/cppkokkos.py) and this is well coded: a single call to **self.state.nested_parse(self.content, self.content_offset, contentnode)** so this is not yet the solution...

**Comment by fnrizzi** [comment]
relatd to #378
