### ISSUE TITLE
sphinx porting: things to add 

### ISSUE THREAD

**Issue by fnrizzi** [kokkos/kokkos-core-wiki#33]
- more visible link to GH page (maybe repo icon at the top?) 
   - [x] propose a few ways to do this 
   - [x] we pick one 
   - [x] finalize 

- [x] we need to make sure each doc page when rendered has a visible link to its rst or md file int the source repo so that if one notices typos or things, one can easily click on the link and be taken to edit that page directly
   - [x] figure out ways to do this and propose 
   - [x] we pick one 
   - [x] finalize

**Comment by marcinwrobel1986** [comment]
Regarding: 
> more visible link to GH page

I would put the link to the documentation at the top of main [README.md](https://github.com/kokkos/kokkos#readme) as it is at the moment. Like marked below:
![Zrzut ekranu z 2022-06-27 14-54-03](https://user-images.githubusercontent.com/47597569/175948321-36fc5a3f-0c21-4e0b-98af-583210b4cdfe.png)

**Comment by marcinwrobel1986** [comment]
Regarding:
> we need to make sure each doc page when rendered has a visible link to its rst or md file int the source repo so that if one notices typos or things, one can easily click on the link and be taken to edit that page directly

1. Localization of files in the repository must be FROZEN
  - when it's not frozen, then links to the code will be broken, each time files are migrated somewhere
  - best would be to agree when documentation is deployed? Once it's merged to develop? Or maybe only  when it's been merged to master branch
  - once there is a consensus, regarding which branch should links point to, these links for editing files could be created
2. Once the files localization is frozen and the branch to which links should point is chosen, then the process of links creation could be defined
  - should it be done by hand? Potential problems:
    - humans makes mistakes
    - one needs to remember to put a link when adding some site in the wiki
  - should it be automated? Possible variants:
    - links is added to the *.md or *.rst file
    - links are added to generated *.html files
  - depending on chosen way (when links are added) a automation script must be written (preferable Python3 one)
3. Regardless of which way of links creation will be chosen, the place where link appears in the wiki page must be defined as well as it's appearance.

SUMMARY:
- location must be final
- I would personally suggest to automate this job
- IMHO the best would be to edit html's after generation, why? Script always have to do the same to html, right? There would be no distinguish between how to put a link in *.md or *.rst file. Adding links to different format probably could be done without a problem, but it adds another level of complexity and it's error prone.

**Comment by marcinwrobel1986** [comment]
Done with https://github.com/kokkos/kokkos-core-wiki/pull/109
Finally an edit icon at the top was chosen. 
After click on the icon it redirects to the file in the GitHub repository on the main branch.
