### ISSUE TITLE
add rst templates for adding documentation

### ISSUE THREAD

**Issue by nmm0** [kokkos/kokkos-core-wiki#362]
Probably will have one for:

- [ ] classes
- [ ] free functions
- [ ] "concepts"

**Comment by masterleinad** [comment]
> @nmm0 -- can we close, given #385?

#385 is not merged.

**Comment by ajpowelsnl** [comment]
> > @nmm0 -- can we close, given #385?
> 
> #385 is not merged.

Understood.  #362 is a subset of #385, and no information is lost by closing #362.

**Comment by nmm0** [comment]
> > > @nmm0 -- can we close, given #385?
> > 
> > 
> > #385 is not merged.
> 
> Understood. #362 is a subset of #385, and no information is lost by closing #362.

This issue will automatically be closed when the PR is merged since it is linked
