### ISSUE TITLE
verify that doc builds warnings-free when 417 is fixed

### ISSUE THREAD

**Issue by fnrizzi** [kokkos/kokkos-core-wiki#433]
according to https://github.com/kokkos/kokkos-core-wiki/issues/420, once https://github.com/kokkos/kokkos-core-wiki/pull/417 is merged, the doc should build without warnings if using all the packages listed in [the requiremtns ](https://github.com/kokkos/kokkos-core-wiki/blob/main/build_requirements.txt). 

We should verify this is the case and report any problems or unexpected behavior.

**Comment by antoinemeyer5** [comment]
I have checked @fnrizzi  and with #417, the doc build without any warnings.

**Comment by fnrizzi** [comment]
i still get these:
```
/kokkos-core-wiki/docs/source/ProgrammingGuide/Atomic-Operations.md:85: WARNING: 'myst' cross-reference target not found: '../API/core/atomics/atomic_op_fetch.md' [myst.xref_missing]
/kokkos-core-wiki/docs/source/ProgrammingGuide/HierarchicalParallelism.md:266: WARNING: 'myst' cross-reference target not found: '../API/core/policies/TeamThreadRange.md' [myst.xref_missing]
/kokkos-core-wiki/docs/source/usecases/MDRangePolicy.md:91: WARNING: 'myst' cross-reference target not found: '../API/core/view/layoutLeft.md' [myst.xref_missing]
```

**Comment by antoinemeyer5** [comment]
> i still get these:
> 
> ```
> /kokkos-core-wiki/docs/source/ProgrammingGuide/Atomic-Operations.md:85: WARNING: 'myst' cross-reference target not found: '../API/core/atomics/atomic_op_fetch.md' [myst.xref_missing]
> /kokkos-core-wiki/docs/source/ProgrammingGuide/HierarchicalParallelism.md:266: WARNING: 'myst' cross-reference target not found: '../API/core/policies/TeamThreadRange.md' [myst.xref_missing]
> /kokkos-core-wiki/docs/source/usecases/MDRangePolicy.md:91: WARNING: 'myst' cross-reference target not found: '../API/core/view/layoutLeft.md' [myst.xref_missing]
> ```

I confirm this error.

However, it does not appear in the CI here: https://github.com/kokkos/kokkos-core-wiki/actions/runs/5464124037/jobs/9945729283

I need to find out why I have missed mistakes. 

Do you have a idea or specific configuration @fnrizzi ?

**Comment by fnrizzi** [comment]
> However, it does not appear in the CI here: https://github.com/kokkos/kokkos-core-wiki/actions/runs/5464124037/jobs/9945729283

it says build finished with problems, 19 warnings.

**Comment by fnrizzi** [comment]
> Do you have a idea or specific configuration @fnrizzi ?

if you tell me how i find out the configation i am happy to share it
