### ISSUE TITLE
Parallel reduce example uses volatile

### ISSUE THREAD

**Issue by nmm0** [kokkos/kokkos-core-wiki#44]
https://github.com/kokkos/kokkos/wiki/ParallelDispatch#732-example-using-functor-with-join-and-init

Per https://github.com/kokkos/kokkos/pull/4931 , the volatile qualifiers in the example should be removed.

Note: we should probably add this after the sphinx conversion. We can note by the example:

```rst
.. versionchanged 3.7
  volatile is no longer required for join()
```

**Comment by nmm0** [comment]
From Damien:

We should provide an example showing how to transition from the old behavior because in some cases the old version would not compile _without_ `volatile`

**Comment by ajpowelsnl** [comment]
@nmm0, @dalg24 -- was this  ever done?  If not, do we still want to do it?  If so, may we close the issue?

**Comment by PhilMiller** [comment]
The main examples and documentation definitely need to *not* use `volatile`. If they're still present, they should be removed.

Any reference to the `volatile` qualifier in relation to our reduction API needs to be clear that it's an anachronism.

**Comment by masterleinad** [comment]
We only mention `volatile` on the deprecation page anymore.
