### ISSUE TITLE
ErrorReporter page is empty

### ISSUE THREAD

**Issue by fnrizzi** [kokkos/kokkos-core-wiki#45]
https://github.com/kokkos/kokkos/wiki/API-Alphabetical

error reporter links to empty page

**Comment by marcinwrobel1986** [comment]
@fnrizzi link to `ErrorReporter` haven't worked. I haven't found any wiki page regarding `ErrorReporter`, so I removed broken link. 
I have only found source files [Kokkos_ErrorReporter.hpp](https://github.com/kokkos/kokkos/blob/master/containers/src/Kokkos_ErrorReporter.hpp) and the test [TestErrorReporter.hpp](https://github.com/kokkos/kokkos/blob/master/containers/unit_tests/TestErrorReporter.hpp)
It seems like `ErrorReporter` is not documented anywhere, but just mentioned in `API in Alphabetical Order`.
