### ISSUE TITLE
Possible Example for reducers:

### ISSUE THREAD

**Issue by crtrott** [kokkos/kokkos-core-wiki#452]
https://godbolt.org/z/r15bhGE7j

**Comment by dalg24** [comment]
The {0.0,0} init value sounds wrong to me.  Why not the minimum representable integer?

**Comment by ajpowelsnl** [comment]
@crtrott , @dalg24 - do you want this example to fall under [parallel_reduce](https://kokkos.github.io/kokkos-core-wiki/API/core/parallel-dispatch/parallel_reduce.html) now, and / or [mdspan](https://github.com/kokkos/mdspan) in the future?

**Comment by ajpowelsnl** [comment]
merged
