### ISSUE TITLE
Update regarding new `set_scratch_size` semantics

### ISSUE THREAD

**Issue by cartoonist** [kokkos/kokkos-core-wiki#491]
As far as I know, `set_scratch_size` member function modifies the instance. However, the documentation, in [HierarchicalParallelism.md](docs/source/ProgrammingGuide/HierarchicalParallelism.md) section, refers to old behaviour:

> Note like previously discussed, the setter function does not modify the instance it is called on, but returns a copy of the policy object with adjusted scratch size request.

I couldn't find where exactly it was "previously discussed" though.

**Comment by dalg24** [comment]
You're correct.
We overlooked the documentation when we changed it (in https://github.com/kokkos/kokkos/pull/4918).
Thank you for reporting the discrepancy.
