### ISSUE TITLE
Add Kokkos_Clamp.hpp & Kokkos_MinMax.hpp to the list of public standalone headers

### ISSUE THREAD

**Issue by nliber** [kokkos/kokkos-core-wiki#516]
From release 4.3:

Add `Kokkos_Clamp.hpp` & `Kokkos_MinMax.hpp` to the list of public standalone headers, to correspond with https://github.com/kokkos/kokkos/pull/6687.

Specifically, it should be added to https://kokkos.org/kokkos-core-wiki/ProgrammingGuide/Compatibility.html (and `Kokkos_Assert.hpp` should be added as well) and documentation for `clamp` to https://kokkos.org/kokkos-core-wiki/API/core/utilities/min_max_clamp.html.

We probably want to add a specific documentation page for public standalone headers.

**Comment by dalg24** [comment]
The headers are mentioned in the notes https://kokkos.org/kokkos-core-wiki/API/core/utilities/min_max_clamp.html#notes

Feel free to improve
