### ISSUE TITLE
Documentation of `ScopeGuard` seems misleading about unhandled exceptions

### ISSUE THREAD

**Issue by JBludau** [kokkos/kokkos-core-wiki#554]
It looks like if an unhandled exception makes it all the way up to `main`, the destructor of `ScopeGuard` is not called.
Nevertheless, the [documentation](https://kokkos.org/kokkos-core-wiki/API/core/initialize_finalize/ScopeGuard.html) seems to promise exactly that.

> ScopeGuard is a class which ensure thats [Kokkos::initialize](https://kokkos.org/kokkos-core-wiki/API/core/initialize_finalize/initialize.html#kokkosinitialize) and [Kokkos::finalize](https://kokkos.org/kokkos-core-wiki/API/core/initialize_finalize/finalize.html#kokkosfinalize) are called correctly even in the presence of unhandled exceptions.

But if the exception reaches `main` it seems to cause immediate termination of the program:
https://godbolt.org/z/Pahs8MW3G

Furthermore, creating an unnamed `ScopeGuard` allows the compiler to call `finalize` immediately after `initialize`;

**Comment by dalg24** [comment]
You're correct.
The standard only guarantees that the destructors will be called if the exception is caught.
https://eel.is/c++draft/except#ctor-1
