### ISSUE TITLE
Strikethrough markdown style not recognized

### ISSUE THREAD

**Issue by dalg24** [kokkos/kokkos-core-wiki#67]
For instance in `html/API/core/numerics/mathematical-functions.html`, `~~` are showing

**Comment by dalg24** [comment]
We could change that table sure.  But we still need a syntax for strikethrough

**Comment by fnrizzi** [comment]
why do we need strikethrough if we can replace that with just an empty entry (or similar) in the table?

**Comment by dalg24** [comment]
I mean in general if we want to use strikethrough elsewhere, not the math functions table

**Comment by fnrizzi** [comment]
yes yes that makes sense! I guess i was talking about this specific use.

**Comment by marcinwrobel1986** [comment]
Hello @dalg24 Damien,
thanks for catching that up. This is really weird behavior.
I proposed the solution in PR #82 
@fnrizzi you can take a look as well
Thanks guys!
